### ISSUE TITLE
[Question] Problem depolying with netlify

### ISSUE THREAD

**Issue by MHYCWasTaken** [hydecorp/hydejack#316]
I deploy with the "Depoly to Netlify" button at https://hydejack.com/docs/install/#new-sites

but it failed

the log:

```
7:18:37 PM: build-image version: 1ca34a93198b041e44214013884c57d146a23fed (focal)
7:18:37 PM: build-image tag: v4.16.4
7:18:37 PM: buildbot version: 30bb0dbce9c066d58cbd3a36ad34f8c91a4777a3
7:18:37 PM: Building without cache
7:18:37 PM: Starting to prepare the repo for build
7:18:38 PM: No cached dependencies found. Cloning fresh repo
7:18:38 PM: git clone --filter=blob:none --no-checkout https://github.com/hydecorp/hydejack-starter-kit
7:18:38 PM: Preparing Git Reference refs/heads/master
7:18:40 PM: Parsing package.json dependencies
7:18:41 PM: Starting build script
7:18:41 PM: Installing dependencies
7:18:41 PM: Python version set to 2.7
7:18:41 PM: v16.19.0 is already installed.
7:18:41 PM: Now using node v16.19.0 (npm v8.19.3)
7:18:41 PM: Enabling Node.js Corepack
7:18:41 PM: Started restoring cached build plugins
7:18:41 PM: Finished restoring cached build plugins
7:18:42 PM: Attempting Ruby version 2.7.1, read from environment
7:18:42 PM: Required ruby-2.7.1 is not installed - installing.
7:18:42 PM: Searching for binary rubies, this might take some time.
7:18:42 PM: Found remote file https://rvm_io.global.ssl.fastly.net/binaries/ubuntu/20.04/x86_64/ruby-2.7.1.tar.bz2
7:18:42 PM: Checking requirements for ubuntu.
7:18:43 PM: Requirements installation successful.
7:18:43 PM: ruby-2.7.1 - #configure
7:18:43 PM: ruby-2.7.1 - #download
7:18:43 PM: ruby-2.7.1 - #validate archive
7:18:46 PM: ruby-2.7.1 - #extract
7:18:49 PM: ruby-2.7.1 - #validate binary
7:18:49 PM: ruby-2.7.1 - #setup
7:18:50 PM: ruby-2.7.1 - #gemset created /opt/buildhome/.rvm/gems/ruby-2.7.1@global
7:18:50 PM: ruby-2.7.1 - #importing gemset /opt/buildhome/.rvm/gemsets/global.gems........................................
7:18:50 PM: ruby-2.7.1 - #generating global wrappers........
7:18:50 PM: ruby-2.7.1 - #gemset created /opt/buildhome/.rvm/gems/ruby-2.7.1
7:18:50 PM: ruby-2.7.1 - #importing gemsetfile /opt/buildhome/.rvm/gemsets/default.gems evaluated to empty gem list
7:18:51 PM: ruby-2.7.1 - #generating default wrappers........
7:18:51 PM: Using /opt/buildhome/.rvm/gems/ruby-2.7.1
7:18:51 PM: Using Ruby version 2.7.1
7:18:51 PM: Using PHP version 8.0
7:18:51 PM: Started restoring cached ruby gems
7:18:51 PM: Finished restoring cached ruby gems
7:18:51 PM: Installing gem bundle
7:18:51 PM: [DEPRECATED] The `--path` flag is deprecated because it relies on being remembered across bundler invocations, which bundler will no longer do in future versions. Instead please use `bundle config set path '/opt/build/cache/bundle'`, and stop using this flag
7:18:51 PM: [DEPRECATED] The --binstubs option will be removed in favor of `bundle binstubs`
7:18:53 PM: Fetching gem metadata from https://rubygems.org/............
7:18:53 PM: Fetching gem metadata from [https://rubygems.org/.](https://rubygems.org/)
7:18:53 PM: Resolving dependencies...
7:18:53 PM: sass-embedded-1.57.1-x86_64-linux-gnu requires rubygems version >= 3.3.22, which
7:18:53 PM: is incompatible with the current version, 3.1.2
7:18:53 PM: Error during gem install
7:18:53 PM: Build was terminated: Build script returned non-zero exit code: 1
7:18:53 PM: Failed during stage 'building site': Build script returned non-zero exit code: 1 (https://ntl.fyi/exit-code-1)
7:18:53 PM: Failing build: Failed to build site
7:18:53 PM: Finished processing build request in 16.226s
```

**Comment by MHYCWasTaken** [comment]
also, i fork the starter kit repository and make it a github pages, i got the same problen
installing sass-embedded, gem version etc

**Comment by MHYCWasTaken** [comment]
well i got this on github pages
```
Could not find 'jekyll-theme-hydejack' (>= 0) among 148 total gem(s)
```
log
```
/usr/bin/docker run --name ghcrioactionsjekyllbuildpagesv104_499cfc --label ea425b --workdir /github/workspace --rm -e "INPUT_SOURCE" -e "INPUT_DESTINATION" -e "INPUT_FUTURE" -e "INPUT_BUILD_REVISION" -e "INPUT_VERBOSE" -e "INPUT_TOKEN" -e "HOME" -e "GITHUB_JOB" -e "GITHUB_REF" -e "GITHUB_SHA" -e "GITHUB_REPOSITORY" -e "GITHUB_REPOSITORY_OWNER" -e "GITHUB_REPOSITORY_OWNER_ID" -e "GITHUB_RUN_ID" -e "GITHUB_RUN_NUMBER" -e "GITHUB_RETENTION_DAYS" -e "GITHUB_RUN_ATTEMPT" -e "GITHUB_REPOSITORY_ID" -e "GITHUB_ACTOR_ID" -e "GITHUB_ACTOR" -e "GITHUB_TRIGGERING_ACTOR" -e "GITHUB_WORKFLOW" -e "GITHUB_HEAD_REF" -e "GITHUB_BASE_REF" -e "GITHUB_EVENT_NAME" -e "GITHUB_SERVER_URL" -e "GITHUB_API_URL" -e "GITHUB_GRAPHQL_URL" -e "GITHUB_REF_NAME" -e "GITHUB_REF_PROTECTED" -e "GITHUB_REF_TYPE" -e "GITHUB_WORKFLOW_REF" -e "GITHUB_WORKFLOW_SHA" -e "GITHUB_WORKSPACE" -e "GITHUB_ACTION" -e "GITHUB_EVENT_PATH" -e "GITHUB_ACTION_REPOSITORY" -e "GITHUB_ACTION_REF" -e "GITHUB_PATH" -e "GITHUB_ENV" -e "GITHUB_STEP_SUMMARY" -e "GITHUB_STATE" -e "GITHUB_OUTPUT" -e "RUNNER_OS" -e "RUNNER_ARCH" -e "RUNNER_NAME" -e "RUNNER_TOOL_CACHE" -e "RUNNER_TEMP" -e "RUNNER_WORKSPACE" -e "ACTIONS_RUNTIME_URL" -e "ACTIONS_RUNTIME_TOKEN" -e "ACTIONS_CACHE_URL" -e "ACTIONS_ID_TOKEN_REQUEST_URL" -e "ACTIONS_ID_TOKEN_REQUEST_TOKEN" -e GITHUB_ACTIONS=true -e CI=true -v "/var/run/docker.sock":"/var/run/docker.sock" -v "/home/runner/work/_temp/_github_home":"/github/home" -v "/home/runner/work/_temp/_github_workflow":"/github/workflow" -v "/home/runner/work/_temp/_runner_file_commands":"/github/file_commands" -v "/home/runner/work/hydejack/hydejack":"/github/workspace" ghcr.io/actions/jekyll-build-pages:v1.0.4
/usr/local/bundle/gems/jekyll-3.9.2/lib/jekyll/theme.rb:84:in `rescue in gemspec': The jekyll-theme-hydejack theme could not be found. (Jekyll::Errors::MissingDependencyException)
	from /usr/local/bundle/gems/jekyll-3.9.2/lib/jekyll/theme.rb:81:in `gemspec'
	from /usr/local/bundle/gems/jekyll-3.9.2/lib/jekyll/theme.rb:19:in `root'
	from /usr/local/bundle/gems/jekyll-3.9.2/lib/jekyll/theme.rb:12:in `initialize'
	from /usr/local/bundle/gems/jekyll-3.9.2/lib/jekyll/site.rb:439:in `new'
	from /usr/local/bundle/gems/jekyll-3.9.2/lib/jekyll/site.rb:439:in `configure_theme'
	from /usr/local/bundle/gems/jekyll-3.9.2/lib/jekyll/site.rb:55:in `config='
	from /usr/local/bundle/gems/jekyll-3.9.2/lib/jekyll/site.rb:23:in `initialize'
	from /usr/local/bundle/gems/jekyll-3.9.2/lib/jekyll/commands/build.rb:30:in `new'
	from /usr/local/bundle/gems/jekyll-3.9.2/lib/jekyll/commands/build.rb:30:in `process'
	from /usr/local/bundle/gems/github-pages-227/bin/github-pages:70:in `block (3 levels) in <top (required)>'
	from /usr/local/bundle/gems/mercenary-0.3.6/lib/mercenary/command.rb:220:in `block in execute'
	from /usr/local/bundle/gems/mercenary-0.3.6/lib/mercenary/command.rb:220:in `each'
	from /usr/local/bundle/gems/mercenary-0.3.6/lib/mercenary/command.rb:220:in `execute'
	from /usr/local/bundle/gems/mercenary-0.3.6/lib/mercenary/program.rb:42:in `go'
	from /usr/local/bundle/gems/mercenary-0.3.6/lib/mercenary.rb:19:in `program'
	from /usr/local/bundle/gems/github-pages-227/bin/github-pages:6:in `<top (required)>'
	from /usr/local/bundle/bin/github-pages:23:in `load'
	from /usr/local/bundle/bin/github-pages:23:in `<main>'
/usr/local/lib/ruby/2.7.0/rubygems/dependency.rb:311:in `to_specs': Could not find 'jekyll-theme-hydejack' (>= 0) among 148 total gem(s) (Gem::MissingSpecError)
  Logging at level: debug
Checked in 'GEM_PATH=/github/home/.gem/ruby/2.7.0:/usr/local/lib/ruby/gems/2.7.0:/usr/local/bundle', execute `gem env` for more information
Configuration file: /github/workspace/./_config.yml
	from /usr/local/lib/ruby/2.7.0/rubygems/dependency.rb:323:in `to_spec'
             Theme: jekyll-theme-hydejack
github-pages 227 | Error:  The jekyll-theme-hydejack theme could not be found.
	from /usr/local/lib/ruby/2.7.0/rubygems/specification.rb:986:in `find_by_name'
	from /usr/local/bundle/gems/jekyll-3.9.2/lib/jekyll/theme.rb:82:in `gemspec'
	from /usr/local/bundle/gems/jekyll-3.9.2/lib/jekyll/theme.rb:19:in `root'
	from /usr/local/bundle/gems/jekyll-3.9.2/lib/jekyll/theme.rb:12:in `initialize'
	from /usr/local/bundle/gems/jekyll-3.9.2/lib/jekyll/site.rb:439:in `new'
	from /usr/local/bundle/gems/jekyll-3.9.2/lib/jekyll/site.rb:439:in `configure_theme'
	from /usr/local/bundle/gems/jekyll-3.9.2/lib/jekyll/site.rb:55:in `config='
	from /usr/local/bundle/gems/jekyll-3.9.2/lib/jekyll/site.rb:23:in `initialize'
	from /usr/local/bundle/gems/jekyll-3.9.2/lib/jekyll/commands/build.rb:30:in `new'
	from /usr/local/bundle/gems/jekyll-3.9.2/lib/jekyll/commands/build.rb:30:in `process'
	from /usr/local/bundle/gems/github-pages-227/bin/github-pages:70:in `block (3 levels) in <top (required)>'
	from /usr/local/bundle/gems/mercenary-0.3.6/lib/mercenary/command.rb:220:in `block in execute'
	from /usr/local/bundle/gems/mercenary-0.3.6/lib/mercenary/command.rb:220:in `each'
	from /usr/local/bundle/gems/mercenary-0.3.6/lib/mercenary/command.rb:220:in `execute'
	from /usr/local/bundle/gems/mercenary-0.3.6/lib/mercenary/program.rb:42:in `go'
	from /usr/local/bundle/gems/mercenary-0.3.6/lib/mercenary.rb:19:in `program'
	from /usr/local/bundle/gems/github-pages-227/bin/github-pages:6:in `<top (required)>'
	from /usr/local/bundle/bin/github-pages:23:in `load'
```

**Comment by shawnyeager** [comment]
I don't know about the starter pack, but I've been deploying the paid/premium Hydejack package to Netlify for 2+ years.

**Comment by MHYCWasTaken** [comment]
> I don't know about the starter pack, but I've been deploying the paid/premium Hydejack package to Netlify for 2+ years.

So it s a problem with the starter kit?

can i have a look at your gemfile and gem version?

**Comment by shawnyeager** [comment]
Sure. 

## Gemfile

```
source "https://rubygems.org"

# Hello! This is where you manage which Jekyll version is used to run.
# When you want to use a different version, change it below, save the
# file and run `bundle install`. Run Jekyll with `bundle exec`, like so:
#
#     bundle exec jekyll serve
#
# This will help ensure the proper Jekyll version is running.
# Happy Jekylling!
gem "jekyll", "~> 4.1"

gem "jekyll-theme-hydejack", path: "./#jekyll-theme-hydejack"

# IMPORTANT: The followign gem is used to compile math formulas to 
# KaTeX during site building.
#
# There are a couple of things to know about this gem:
# *  It is not supported on GitHub Pages. 
#    You have to build the site on your machine before uploading to GitHub,
#    or use a more permissive cloud building tool such as Netlify.
# *  You need some kind of JavaScript runtime on your machine.
#    Usually installing NodeJS will suffice. 
#    For details, see <https://github.com/kramdown/math-katex#documentation>
#
# If you're using the MathJax math engine instead, free to remove the line below:
gem "kramdown-math-katex"

group :jekyll_plugins do
  gem "jekyll-feed"
  gem "jekyll-optional-front-matter"
  gem "jekyll-paginate"
  gem "jekyll-readme-index"
  gem "jekyll-redirect-from"
  gem "jekyll-relative-links"
  gem "jekyll-seo-tag", git: "https://github.com/hydecorp/jekyll-seo-tag"
  gem "jekyll-sitemap"
  gem "jekyll-titles-from-headings"
  gem "jekyll-include-cache", git: "https://github.com/hydecorp/jekyll-include-cache"
  gem "jekyll-last-modified-at"
  gem "jekyll-compose"
end

gem 'rake'
gem 'html-proofer'

gem 'wdm' if Gem.win_platform?
gem "tzinfo-data" if Gem.win_platform?

gem "webrick", "~> 1.7"
```

## Gemfile.lock

```

GIT
  remote: https://github.com/hydecorp/jekyll-include-cache
  revision: 2168263a7c88101f92557e6fe015a276267d8274
  specs:
    jekyll-include-cache (0.2.0)
      jekyll (>= 3.7, < 5.0)

GIT
  remote: https://github.com/hydecorp/jekyll-seo-tag
  revision: 6135021410981d2d76878568e9c21cf363882bfe
  specs:
    jekyll-seo-tag (2.6.1)
      jekyll (>= 3.3, < 5.0)

PATH
  remote: #jekyll-theme-hydejack
  specs:
    jekyll-theme-hydejack (9.1.6)
      jekyll (>= 3.8, < 5.0)
      jekyll-include-cache (~> 0.2)

GEM
  remote: https://rubygems.org/
  specs:
    Ascii85 (1.1.0)
    addressable (2.8.1)
      public_suffix (>= 2.0.2, < 6.0)
    afm (0.2.2)
    async (2.3.1)
      console (~> 1.10)
      io-event (~> 1.1)
      timers (~> 4.1)
    colorator (1.1.0)
    concurrent-ruby (1.2.0)
    console (1.16.2)
      fiber-local
    em-websocket (0.5.3)
      eventmachine (>= 0.12.9)
      http_parser.rb (~> 0)
    ethon (0.16.0)
      ffi (>= 1.15.0)
    eventmachine (1.2.7)
    execjs (2.8.1)
    ffi (1.15.5)
    fiber-local (1.0.0)
    forwardable-extended (2.6.0)
    google-protobuf (3.21.12)
    hashery (2.1.2)
    html-proofer (5.0.4)
      addressable (~> 2.3)
      async (~> 2.1)
      nokogiri (~> 1.13)
      pdf-reader (~> 2.11)
      rainbow (~> 3.0)
      typhoeus (~> 1.3)
      yell (~> 2.0)
      zeitwerk (~> 2.5)
    http_parser.rb (0.8.0)
    i18n (1.12.0)
      concurrent-ruby (~> 1.0)
    io-event (1.1.6)
    jekyll (4.3.2)
      addressable (~> 2.4)
      colorator (~> 1.0)
      em-websocket (~> 0.5)
      i18n (~> 1.0)
      jekyll-sass-converter (>= 2.0, < 4.0)
      jekyll-watch (~> 2.0)
      kramdown (~> 2.3, >= 2.3.1)
      kramdown-parser-gfm (~> 1.0)
      liquid (~> 4.0)
      mercenary (>= 0.3.6, < 0.5)
      pathutil (~> 0.9)
      rouge (>= 3.0, < 5.0)
      safe_yaml (~> 1.0)
      terminal-table (>= 1.8, < 4.0)
      webrick (~> 1.7)
    jekyll-compose (0.12.0)
      jekyll (>= 3.7, < 5.0)
    jekyll-feed (0.17.0)
      jekyll (>= 3.7, < 5.0)
    jekyll-last-modified-at (1.3.0)
      jekyll (>= 3.7, < 5.0)
      posix-spawn (~> 0.3.9)
    jekyll-optional-front-matter (0.3.2)
      jekyll (>= 3.0, < 5.0)
    jekyll-paginate (1.1.0)
    jekyll-readme-index (0.3.0)
      jekyll (>= 3.0, < 5.0)
    jekyll-redirect-from (0.16.0)
      jekyll (>= 3.3, < 5.0)
    jekyll-relative-links (0.7.0)
      jekyll (>= 3.3, < 5.0)
    jekyll-sass-converter (3.0.0)
      sass-embedded (~> 1.54)
    jekyll-sitemap (1.4.0)
      jekyll (>= 3.7, < 5.0)
    jekyll-titles-from-headings (0.5.3)
      jekyll (>= 3.3, < 5.0)
    jekyll-watch (2.2.1)
      listen (~> 3.0)
    katex (0.9.0)
      execjs (~> 2.7)
    kramdown (2.4.0)
      rexml
    kramdown-math-katex (1.0.1)
      katex (~> 0.4)
      kramdown (~> 2.0)
    kramdown-parser-gfm (1.1.0)
      kramdown (~> 2.0)
    liquid (4.0.4)
    listen (3.8.0)
      rb-fsevent (~> 0.10, >= 0.10.3)
      rb-inotify (~> 0.9, >= 0.9.10)
    mercenary (0.4.0)
    mini_portile2 (2.8.1)
    nokogiri (1.14.0)
      mini_portile2 (~> 2.8.0)
      racc (~> 1.4)
    pathutil (0.16.2)
      forwardable-extended (~> 2.6)
    pdf-reader (2.11.0)
      Ascii85 (~> 1.0)
      afm (~> 0.2.1)
      hashery (~> 2.0)
      ruby-rc4
      ttfunk
    posix-spawn (0.3.15)
    public_suffix (5.0.1)
    racc (1.6.2)
    rainbow (3.1.1)
    rake (13.0.6)
    rb-fsevent (0.11.2)
    rb-inotify (0.10.1)
      ffi (~> 1.0)
    rexml (3.2.5)
    rouge (4.0.1)
    ruby-rc4 (0.1.5)
    safe_yaml (1.0.5)
    sass-embedded (1.57.1)
      google-protobuf (~> 3.21)
      rake (>= 10.0.0)
    terminal-table (3.0.2)
      unicode-display_width (>= 1.1.1, < 3)
    timers (4.3.5)
    ttfunk (1.7.0)
    typhoeus (1.4.0)
      ethon (>= 0.9.0)
    unicode-display_width (2.4.2)
    webrick (1.8.1)
    yell (2.2.2)
    zeitwerk (2.6.6)

PLATFORMS
  ruby

DEPENDENCIES
  html-proofer
  jekyll (~> 4.1)
  jekyll-compose
  jekyll-feed
  jekyll-include-cache!
  jekyll-last-modified-at
  jekyll-optional-front-matter
  jekyll-paginate
  jekyll-readme-index
  jekyll-redirect-from
  jekyll-relative-links
  jekyll-seo-tag!
  jekyll-sitemap
  jekyll-theme-hydejack!
  jekyll-titles-from-headings
  kramdown-math-katex
  rake
  webrick (~> 1.7)

BUNDLED WITH
   2.3.24
```

**Comment by MHYCWasTaken** [comment]
okay
it seems like a problem with gem source
this is my source `https://gems.ruby-china.com/`
the default source in my country is too slow
maybe i can just go get a vpn

**Comment by public-learner** [comment]
Hi @MHYCWasTaken , I'm just getting the same error. Were you able to fix this problem?

**Comment by mcrimaldi** [comment]
I have the same problem, anyone got a solution for this? HydeJack Starter version
