### ISSUE TITLE
Issues deploying to vercel

### ISSUE THREAD

**Issue by TechClusterHQ** [hydecorp/hydejack#324]
I'm currently facing issues deploying hydejack to vercel:

```
<html>
<body>
<!--StartFragment-->

Error: error:0308010C:digital envelope routines::unsupported
--
12:10:09.350 | at new Hash (node:internal/crypto/hash:71:19)
12:10:09.350 | at Object.createHash (node:crypto:133:10)
12:10:09.350 | at module.exports (/vercel/path0/node_modules/webpack/lib/util/createHash.js:135:53)
12:10:09.351 | at NormalModule._initBuildHash (/vercel/path0/node_modules/webpack/lib/NormalModule.js:417:16)
12:10:09.351 | at handleParseError (/vercel/path0/node_modules/webpack/lib/NormalModule.js:471:10)
12:10:09.351 | at /vercel/path0/node_modules/webpack/lib/NormalModule.js:503:5
12:10:09.351 | at /vercel/path0/node_modules/webpack/lib/NormalModule.js:358:12
12:10:09.351 | at /vercel/path0/node_modules/loader-runner/lib/LoaderRunner.js:373:3
12:10:09.351 | at iterateNormalLoaders (/vercel/path0/node_modules/loader-runner/lib/LoaderRunner.js:214:10)
12:10:09.352 | at iterateNormalLoaders (/vercel/path0/node_modules/loader-runner/lib/LoaderRunner.js:221:10)
12:10:09.352 | at /vercel/path0/node_modules/loader-runner/lib/LoaderRunner.js:236:3
12:10:09.352 | at context.callback (/vercel/path0/node_modules/loader-runner/lib/LoaderRunner.js:111:13)
12:10:09.352 | at /vercel/path0/node_modules/babel-loader/lib/index.js:59:71
12:10:09.352 | at process.processTicksAndRejections (node:internal/process/task_queues:95:5) {
12:10:09.352 | opensslErrorStack: [ 'error:03000086:digital envelope routines::initialization error' ],
12:10:09.352 | library: 'digital envelope routines',
12:10:09.353 | reason: 'unsupported',
12:10:09.353 | code: 'ERR_OSSL_EVP_UNSUPPORTED'
12:10:09.353 | }
12:10:09.353 |  
12:10:09.353 | Node.js v18.16.1
12:10:09.524 | Error: No Output Directory named "_site" found after the Build completed. You can configure the Output Directory in your Project Settings.

<!--EndFragment-->
</body>
</html>
```

Is there an easy deploy link for vercel like it exists for netlify (found in the readme)?

**Comment by TechClusterHQ** [comment]
stale
